# Kustomization File: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/
resources:
# 全環境共通の定義が記述されたマニフェストファイルを指定
- namespace.yaml
- app.yaml

configMapGenerator:
  - name: sample-app-config
    literals:
      - STAGE=prod